In [59]:
import pandas as pd

In [60]:
spd1 = pd.read_csv('/Users/noshintasnim/Downloads/Solar Power Generation Project/Raw Data/solar_plant_generation_dataset.csv')

In [61]:
spd1.head(10)

,timestamp,solar_irradiance_wm2,ambient_temperature_c,panel_temperature_c,cloud_cover_percent,power_generation_kw
0,2025-01-01 00:00:00,0.00,23.06,23.06,35.37,0.00
1,2025-01-01 01:00:00,0.00,28.04,28.04,20.70,0.00
2,2025-01-01 02:00:00,0.00,24.97,24.97,16.00,0.00
3,2025-01-01 03:00:00,0.00,17.90,17.90,3.14,0.00
4,2025-01-01 04:00:00,0.00,24.27,24.27,25.09,0.00
5,2025-01-01 05:00:00,0.00,21.94,21.94,7.86,0.00
6,2025-01-01 06:00:00,0.00,29.03,29.03,32.08,0.00
7,2025-01-01 07:00:00,162.82,34.43,36.47,55.19,19.08
8,2025-01-01 08:00:00,356.83,26.77,31.23,16.65,61.90
9,2025-01-01 09:00:00,415.52,25.94,31.13,35.33,62.83

In [62]:
spd1.columns

Index(['timestamp', 'solar_irradiance_wm2', 'ambient_temperature_c',
       'panel_temperature_c', 'cloud_cover_percent', 'power_generation_kw'],
      dtype='object')

In [63]:
spd1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   timestamp              5000 non-null   object
 1   solar_irradiance_wm2   5000 non-null   float64
 2   ambient_temperature_c  5000 non-null   float64
 3   panel_temperature_c    5000 non-null   float64
 4   cloud_cover_percent    5000 non-null   float64
 5   power_generation_kw    5000 non-null   float64
dtypes: float64(5), object(1)
memory usage: 234.5+ KB

In [64]:
spd1 =spd1.rename(columns={'timestamp': 'Timestamp', 'solar_irradiance_wm2': 'Irradiance', 'ambient_temperature_c': 'Ambient_Temperature',
                    'panel_temperature_c': 'Module_Temperature','cloud_cover_percent': 'Cloud_Cover',
                    'power_generation_kw': 'Power_Generation'})

spd1.insert(1, 'Plant_ID', 4137001)

In [65]:
spd1.head(24)

,Timestamp,Plant_ID,Irradiance,Ambient_Temperature,Module_Temperature,Cloud_Cover,Power_Generation
0,2025-01-01 00:00:00,4137001,0.00,23.06,23.06,35.37,0.00
1,2025-01-01 01:00:00,4137001,0.00,28.04,28.04,20.70,0.00
2,2025-01-01 02:00:00,4137001,0.00,24.97,24.97,16.00,0.00
3,2025-01-01 03:00:00,4137001,0.00,17.90,17.90,3.14,0.00
4,2025-01-01 04:00:00,4137001,0.00,24.27,24.27,25.09,0.00
5,2025-01-01 05:00:00,4137001,0.00,21.94,21.94,7.86,0.00
6,2025-01-01 06:00:00,4137001,0.00,29.03,29.03,32.08,0.00
7,2025-01-01 07:00:00,4137001,162.82,34.43,36.47,55.19,19.08
8,2025-01-01 08:00:00,4137001,356.83,26.77,31.23,16.65,61.90
9,2025-01-01 09:00:00,4137001,415.52,25.94,31.13,35.33,62.83
10,2025-01-01 10:00:00,4137001,694.01,26.26,34.93,42.91,94.64
11,2025-01-01 11:00:00,4137001,769.97,34.88,44.50,20.77,142.37
12,2025-01-01 12:00:00,4137001,716.99,34.77,43.74,31.91,104.78
13,2025-01-01 13:00:00,4137001,813.50,30.52,40.69,0.84,148.80
14,2025-01-01 14:00:00,4137001,631.78,28.73,36.62,33.44,87.26
15,2025-01-01 15:00:00,4137001,538.01,33.08,39.80,50.28,74.97
16,2025-01-01 16:00:00,4137001,367.96,37.64,42.24,17.14,59.47
17,2025-01-01 17:00:00,4137001,134.43,25.19,26.87,35.20,19.55
18,2025-01-01 18:00:00,4137001,0.00,29.89,29.89,7.91,0.00
19,2025-01-01 19:00:00,4137001,0.00,21.36,21.36,18.19,0.00
20,2025-01-01 20:00:00,4137001,0.00,25.21,25.21,28.17,0.00
21,2025-01-01 21:00:00,4137001,0.00,20.90,20.90,31.56,0.00
22,2025-01-01 22:00:00,4137001,0.00,18.39,18.39,25.51,0.00
23,2025-01-01 23:00:00,4137001,0.00,30.83,30.83,13.72,0.00

In [66]:
spd1.isna().any()

Timestamp              False
Plant_ID               False
Irradiance             False
Ambient_Temperature    False
Module_Temperature     False
Cloud_Cover            False
Power_Generation       False
dtype: bool