In [487]:
import pandas as pd

In [488]:
gd1 = pd.read_csv('/Users/noshintasnim/Downloads/Solar Power Generation Project/Raw Data/Plant_Generation_&_Weather_censor_Data/Plant_1_Generation_Data.csv')
gd2 = pd.read_csv('/Users/noshintasnim/Downloads/Solar Power Generation Project/Raw Data/Plant_Generation_&_Weather_censor_Data/Plant_2_Generation_Data.csv')
wsd1 = pd.read_csv('/Users/noshintasnim/Downloads/Solar Power Generation Project/Raw Data/Plant_Generation_&_Weather_censor_Data/Plant_1_Weather_Sensor_Data.csv')
wsd2 = pd.read_csv('/Users/noshintasnim/Downloads/Solar Power Generation Project/Raw Data/Plant_Generation_&_Weather_censor_Data/Plant_2_Weather_Sensor_Data.csv')

In [489]:
gd1.iloc[0:23]

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD
0,15-05-2020 00:00,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6259559.0
1,15-05-2020 00:00,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.0,6183645.0
2,15-05-2020 00:00,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.0,6987759.0
3,15-05-2020 00:00,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.0,7602960.0
4,15-05-2020 00:00,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.0,7158964.0
5,15-05-2020 00:00,4135001,VHMLBKoKgIrUVDU,0.0,0.0,0.0,7206408.0
6,15-05-2020 00:00,4135001,WRmjgnKYAwPKWDb,0.0,0.0,0.0,7028673.0
7,15-05-2020 00:00,4135001,ZnxXDlPa8U1GXgE,0.0,0.0,0.0,6522172.0
8,15-05-2020 00:00,4135001,ZoEaEvLYb1n2sOq,0.0,0.0,0.0,7098099.0
9,15-05-2020 00:00,4135001,adLQvlD726eNBSB,0.0,0.0,0.0,6271355.0
10,15-05-2020 00:00,4135001,bvBOhCH3iADSZry,0.0,0.0,0.0,6316803.0
11,15-05-2020 00:00,4135001,iCRJl6heRkivqQ3,0.0,0.0,0.0,7177992.0
12,15-05-2020 00:00,4135001,ih0vzX44oOqAx2f,0.0,0.0,0.0,6185184.0
13,15-05-2020 00:00,4135001,pkci93gMrogZuBj,0.0,0.0,0.0,7169102.0
14,15-05-2020 00:00,4135001,rGa61gmuvPhdLxV,0.0,0.0,0.0,7111493.0
15,15-05-2020 00:00,4135001,sjndEbLyjtCKgGv,0.0,0.0,0.0,7016832.0
16,15-05-2020 00:00,4135001,uHbuxQJl8lW7ozc,0.0,0.0,0.0,7038681.0
17,15-05-2020 00:00,4135001,wCURE6d3bPkepu2,0.0,0.0,0.0,6782598.0
18,15-05-2020 00:00,4135001,z9Y9gH1T5YWrNuG,0.0,0.0,0.0,7007866.0
19,15-05-2020 00:00,4135001,zBIq5rxdHJRwDNY,0.0,0.0,0.0,6339380.0
20,15-05-2020 00:00,4135001,zVJPv84UY57bAof,0.0,0.0,0.0,7116151.0
21,15-05-2020 00:15,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6259559.0
22,15-05-2020 00:15,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.0,6183645.0

In [490]:
gd2.head(10)

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD
0,2020-05-15 00:00:00,4136001,4UPUqMRk7TRMgml,0.0,0.0,9425.000000,2.429011e+06
1,2020-05-15 00:00:00,4136001,81aHJ1q11NBPMrL,0.0,0.0,0.000000,1.215279e+09
2,2020-05-15 00:00:00,4136001,9kRcWv60rDACzjR,0.0,0.0,3075.333333,2.247720e+09
3,2020-05-15 00:00:00,4136001,Et9kgGMDl729KT4,0.0,0.0,269.933333,1.704250e+06
4,2020-05-15 00:00:00,4136001,IQ2d7wF4YD8zU1Q,0.0,0.0,3177.000000,1.994153e+07
5,2020-05-15 00:00:00,4136001,LYwnQax7tkwH5Cb,0.0,0.0,1872.500000,1.794959e+09
6,2020-05-15 00:00:00,4136001,LlT2YUhhzqhg5Sw,0.0,0.0,1094.357143,2.825928e+08
7,2020-05-15 00:00:00,4136001,Mx2yZCDsyf6DPfv,0.0,0.0,5692.200000,2.453646e+06
8,2020-05-15 00:00:00,4136001,NgDl19wMapZy17u,0.0,0.0,1866.200000,1.115126e+08
9,2020-05-15 00:00:00,4136001,PeE6FRyGXUgsRhN,0.0,0.0,651.200000,1.348351e+09

In [491]:
wsd1.tail(20)

,DATE_TIME,PLANT_ID,SOURCE_KEY,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
3162,2020-06-17 19:00:00,4135001,HmiyD2TTLFNqkNe,23.474888,22.423350,0.0
3163,2020-06-17 19:15:00,4135001,HmiyD2TTLFNqkNe,23.489280,22.756881,0.0
3164,2020-06-17 19:30:00,4135001,HmiyD2TTLFNqkNe,23.455611,22.717605,0.0
3165,2020-06-17 19:45:00,4135001,HmiyD2TTLFNqkNe,23.051322,21.774304,0.0
3166,2020-06-17 20:00:00,4135001,HmiyD2TTLFNqkNe,23.003263,21.243221,0.0
3167,2020-06-17 20:15:00,4135001,HmiyD2TTLFNqkNe,22.890356,20.784727,0.0
3168,2020-06-17 20:30:00,4135001,HmiyD2TTLFNqkNe,22.891966,20.949461,0.0
3169,2020-06-17 20:45:00,4135001,HmiyD2TTLFNqkNe,22.887429,21.121948,0.0
3170,2020-06-17 21:00:00,4135001,HmiyD2TTLFNqkNe,22.899882,21.383107,0.0
3171,2020-06-17 21:15:00,4135001,HmiyD2TTLFNqkNe,22.892598,21.563179,0.0
3172,2020-06-17 21:30:00,4135001,HmiyD2TTLFNqkNe,22.996562,21.869773,0.0
3173,2020-06-17 21:45:00,4135001,HmiyD2TTLFNqkNe,23.137091,22.125985,0.0
3174,2020-06-17 22:00:00,4135001,HmiyD2TTLFNqkNe,22.563179,21.164713,0.0
3175,2020-06-17 22:15:00,4135001,HmiyD2TTLFNqkNe,22.199229,20.515273,0.0
3176,2020-06-17 22:30:00,4135001,HmiyD2TTLFNqkNe,22.171737,21.080829,0.0
3177,2020-06-17 22:45:00,4135001,HmiyD2TTLFNqkNe,22.150570,21.480377,0.0
3178,2020-06-17 23:00:00,4135001,HmiyD2TTLFNqkNe,22.129816,21.389024,0.0
3179,2020-06-17 23:15:00,4135001,HmiyD2TTLFNqkNe,22.008275,20.709211,0.0
3180,2020-06-17 23:30:00,4135001,HmiyD2TTLFNqkNe,21.969495,20.734963,0.0
3181,2020-06-17 23:45:00,4135001,HmiyD2TTLFNqkNe,21.909288,20.427972,0.0

In [492]:
wsd2.head(10)

,DATE_TIME,PLANT_ID,SOURCE_KEY,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
0,2020-05-15 00:00:00,4136001,iq8k7ZNt4Mwm3w0,27.004764,25.060789,0.0
1,2020-05-15 00:15:00,4136001,iq8k7ZNt4Mwm3w0,26.880811,24.421869,0.0
2,2020-05-15 00:30:00,4136001,iq8k7ZNt4Mwm3w0,26.682055,24.427290,0.0
3,2020-05-15 00:45:00,4136001,iq8k7ZNt4Mwm3w0,26.500589,24.420678,0.0
4,2020-05-15 01:00:00,4136001,iq8k7ZNt4Mwm3w0,26.596148,25.088210,0.0
5,2020-05-15 01:15:00,4136001,iq8k7ZNt4Mwm3w0,26.512740,25.317970,0.0
6,2020-05-15 01:30:00,4136001,iq8k7ZNt4Mwm3w0,26.494339,25.217193,0.0
7,2020-05-15 01:45:00,4136001,iq8k7ZNt4Mwm3w0,26.420410,25.065062,0.0
8,2020-05-15 02:00:00,4136001,iq8k7ZNt4Mwm3w0,26.401946,24.691469,0.0
9,2020-05-15 02:15:00,4136001,iq8k7ZNt4Mwm3w0,26.226078,24.559481,0.0

In [493]:
gd1.columns

Index(['DATE_TIME', 'PLANT_ID', 'SOURCE_KEY', 'DC_POWER', 'AC_POWER',
       'DAILY_YIELD', 'TOTAL_YIELD'],
      dtype='object')

In [494]:
gd2.columns

Index(['DATE_TIME', 'PLANT_ID', 'SOURCE_KEY', 'DC_POWER', 'AC_POWER',
       'DAILY_YIELD', 'TOTAL_YIELD'],
      dtype='object')

In [495]:
wsd1.columns

Index(['DATE_TIME', 'PLANT_ID', 'SOURCE_KEY', 'AMBIENT_TEMPERATURE',
       'MODULE_TEMPERATURE', 'IRRADIATION'],
      dtype='object')

In [496]:
wsd2.columns

Index(['DATE_TIME', 'PLANT_ID', 'SOURCE_KEY', 'AMBIENT_TEMPERATURE',
       'MODULE_TEMPERATURE', 'IRRADIATION'],
      dtype='object')

In [497]:
gd1['DATE_TIME'] = pd.to_datetime(gd1['DATE_TIME'], errors='coerce')
gd2['DATE_TIME'] = pd.to_datetime(gd2['DATE_TIME'], errors='coerce')
wsd1['DATE_TIME'] = pd.to_datetime(wsd1['DATE_TIME'], errors='coerce')
wsd2['DATE_TIME'] = pd.to_datetime(wsd2['DATE_TIME'], errors='coerce')

/var/folders/_n/cccmfm1j1h758yhhqvxs_1kw0000gn/T/ipykernel_63888/3295663697.py:1: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  gd1['DATE_TIME'] = pd.to_datetime(gd1['DATE_TIME'], errors='coerce')

In [498]:
gd1.head(10)

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD
0,2020-05-15,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6259559.0
1,2020-05-15,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.0,6183645.0
2,2020-05-15,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.0,6987759.0
3,2020-05-15,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.0,7602960.0
4,2020-05-15,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.0,7158964.0
5,2020-05-15,4135001,VHMLBKoKgIrUVDU,0.0,0.0,0.0,7206408.0
6,2020-05-15,4135001,WRmjgnKYAwPKWDb,0.0,0.0,0.0,7028673.0
7,2020-05-15,4135001,ZnxXDlPa8U1GXgE,0.0,0.0,0.0,6522172.0
8,2020-05-15,4135001,ZoEaEvLYb1n2sOq,0.0,0.0,0.0,7098099.0
9,2020-05-15,4135001,adLQvlD726eNBSB,0.0,0.0,0.0,6271355.0

In [499]:
gd1_agg = gd1.groupby('DATE_TIME').agg({'PLANT_ID': 'first', 'DC_POWER': 'sum', 'AC_POWER': 'sum', 'DAILY_YIELD': 'sum'}).reset_index()

In [500]:
gd1_agg.iloc[55:75]

             DATE_TIME  PLANT_ID       DC_POWER      AC_POWER    DAILY_YIELD
55 2020-05-15 13:45:00   4135001  170970.589284  16736.742858   89618.464288
56 2020-05-15 14:00:00   4135001  222438.714294  21747.066071   94351.839285
57 2020-05-15 14:15:00   4135001  259813.285720  25352.546429  100265.464287
58 2020-05-15 14:30:00   4135001  142901.932142  13989.196071  105649.507142
59 2020-05-15 14:45:00   4135001  160715.529762  15723.055357  108951.898810
60 2020-05-15 15:00:00   4135001  128604.375000  12603.766072  112657.625000
61 2020-05-15 15:15:00   4135001  143255.142856  14031.026786  115985.999999
62 2020-05-15 15:30:00   4135001  166946.321430  16342.919643  119794.523810
63 2020-05-15 15:45:00   4135001  107547.160714  10543.766071  122858.380952
64 2020-05-15 16:00:00   4135001  109120.678571  10704.023214  125887.767858
65 2020-05-15 16:15:00   4135001   99493.017857   9763.446429  128208.535714
66 2020-05-15 16:30:00   4135001  104079.607143  10210.664286  130816.017856
67 2020-05-15 16:45:00   4135001   77777.196429   7643.759524  133059.166667
68 2020-05-15 17:00:00   4135001   49913.767857   4894.992857  134620.839284
69 2020-05-15 17:15:00   4135001   49718.660716   4875.005357  135859.303572
70 2020-05-15 17:30:00   4135001   26248.833333   2558.016667  136646.750000
71 2020-05-15 17:45:00   4135001   11391.250000   1102.005357  137121.857143
72 2020-05-15 18:00:00   4135001    6505.000000    628.376786  137350.446429
73 2020-05-15 18:15:00   4135001    2199.217857    212.151786  137449.607144
74 2020-05-15 18:30:00   4135001       0.000000      0.000000  137473.000000

In [501]:
gd2_agg = gd2.groupby('DATE_TIME').agg({'PLANT_ID': 'first', 'DC_POWER': 'sum', 'AC_POWER': 'sum', 'DAILY_YIELD': 'sum'}).reset_index()

In [502]:
gd2_agg.head(10)

            DATE_TIME  PLANT_ID  DC_POWER  AC_POWER   DAILY_YIELD
0 2020-05-15 00:00:00   4136001       0.0       0.0  48899.938095
1 2020-05-15 00:15:00   4136001       0.0       0.0  28401.000000
2 2020-05-15 00:30:00   4136001       0.0       0.0  28401.000000
3 2020-05-15 00:45:00   4136001       0.0       0.0  28401.000000
4 2020-05-15 01:00:00   4136001       0.0       0.0  26516.000000
5 2020-05-15 01:15:00   4136001       0.0       0.0  18976.000000
6 2020-05-15 01:30:00   4136001       0.0       0.0  18976.000000
7 2020-05-15 01:45:00   4136001       0.0       0.0  18976.000000
8 2020-05-15 02:00:00   4136001       0.0       0.0  18976.000000
9 2020-05-15 02:15:00   4136001       0.0       0.0  18976.000000

In [503]:
combined_pl1 = pd.merge(gd1_agg, wsd1, on=['DATE_TIME', 'PLANT_ID'], how='left')

In [504]:
combined_pl1.head(10)

,DATE_TIME,PLANT_ID,DC_POWER,AC_POWER,DAILY_YIELD,SOURCE_KEY,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
0,2020-05-15 00:00:00,4135001,0.0,0.0,0.0,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
1,2020-05-15 00:15:00,4135001,0.0,0.0,0.0,HmiyD2TTLFNqkNe,25.084589,22.761668,0.0
2,2020-05-15 00:30:00,4135001,0.0,0.0,0.0,HmiyD2TTLFNqkNe,24.935753,22.592306,0.0
3,2020-05-15 00:45:00,4135001,0.0,0.0,0.0,HmiyD2TTLFNqkNe,24.846130,22.360852,0.0
4,2020-05-15 01:00:00,4135001,0.0,0.0,0.0,HmiyD2TTLFNqkNe,24.621525,22.165423,0.0
5,2020-05-15 01:15:00,4135001,0.0,0.0,0.0,HmiyD2TTLFNqkNe,24.536092,21.968571,0.0
6,2020-05-15 01:30:00,4135001,0.0,0.0,0.0,HmiyD2TTLFNqkNe,24.638674,22.352926,0.0
7,2020-05-15 01:45:00,4135001,0.0,0.0,0.0,HmiyD2TTLFNqkNe,24.873022,23.160919,0.0
8,2020-05-15 02:00:00,4135001,0.0,0.0,0.0,HmiyD2TTLFNqkNe,24.936930,23.026113,0.0
9,2020-05-15 02:15:00,4135001,0.0,0.0,0.0,HmiyD2TTLFNqkNe,25.012248,23.343229,0.0

In [505]:
combined_pl2 = pd.merge(gd2_agg, wsd2, on=['DATE_TIME', 'PLANT_ID'], how='left')

In [506]:
combined_pl2.head(10)

,DATE_TIME,PLANT_ID,DC_POWER,AC_POWER,DAILY_YIELD,SOURCE_KEY,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
0,2020-05-15 00:00:00,4136001,0.0,0.0,48899.938095,iq8k7ZNt4Mwm3w0,27.004764,25.060789,0.0
1,2020-05-15 00:15:00,4136001,0.0,0.0,28401.000000,iq8k7ZNt4Mwm3w0,26.880811,24.421869,0.0
2,2020-05-15 00:30:00,4136001,0.0,0.0,28401.000000,iq8k7ZNt4Mwm3w0,26.682055,24.427290,0.0
3,2020-05-15 00:45:00,4136001,0.0,0.0,28401.000000,iq8k7ZNt4Mwm3w0,26.500589,24.420678,0.0
4,2020-05-15 01:00:00,4136001,0.0,0.0,26516.000000,iq8k7ZNt4Mwm3w0,26.596148,25.088210,0.0
5,2020-05-15 01:15:00,4136001,0.0,0.0,18976.000000,iq8k7ZNt4Mwm3w0,26.512740,25.317970,0.0
6,2020-05-15 01:30:00,4136001,0.0,0.0,18976.000000,iq8k7ZNt4Mwm3w0,26.494339,25.217193,0.0
7,2020-05-15 01:45:00,4136001,0.0,0.0,18976.000000,iq8k7ZNt4Mwm3w0,26.420410,25.065062,0.0
8,2020-05-15 02:00:00,4136001,0.0,0.0,18976.000000,iq8k7ZNt4Mwm3w0,26.401946,24.691469,0.0
9,2020-05-15 02:15:00,4136001,0.0,0.0,18976.000000,iq8k7ZNt4Mwm3w0,26.226078,24.559481,0.0

In [507]:
spd2 = pd.concat([combined_pl1, combined_pl2], axis=0, ignore_index=True)

In [508]:
spd2.iloc[55:75]

,DATE_TIME,PLANT_ID,DC_POWER,AC_POWER,DAILY_YIELD,SOURCE_KEY,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
55,2020-05-15 13:45:00,4135001,170970.589284,16736.742858,89618.464288,HmiyD2TTLFNqkNe,32.678471,47.516884,0.560986
56,2020-05-15 14:00:00,4135001,222438.714294,21747.066071,94351.839285,HmiyD2TTLFNqkNe,33.763185,49.803904,0.735083
57,2020-05-15 14:15:00,4135001,259813.285720,25352.546429,100265.464287,HmiyD2TTLFNqkNe,34.130770,55.030613,0.893661
58,2020-05-15 14:30:00,4135001,142901.932142,13989.196071,105649.507142,HmiyD2TTLFNqkNe,34.081384,54.519137,0.466789
59,2020-05-15 14:45:00,4135001,160715.529762,15723.055357,108951.898810,HmiyD2TTLFNqkNe,33.695722,47.618195,0.542138
60,2020-05-15 15:00:00,4135001,128604.375000,12603.766072,112657.625000,HmiyD2TTLFNqkNe,33.890576,46.029081,0.398889
61,2020-05-15 15:15:00,4135001,143255.142856,14031.026786,115985.999999,HmiyD2TTLFNqkNe,34.043744,44.286092,0.447292
62,2020-05-15 15:30:00,4135001,166946.321430,16342.919643,119794.523810,HmiyD2TTLFNqkNe,34.402852,46.744281,0.565196
63,2020-05-15 15:45:00,4135001,107547.160714,10543.766071,122858.380952,HmiyD2TTLFNqkNe,34.430943,43.920616,0.346231
64,2020-05-15 16:00:00,4135001,109120.678571,10704.023214,125887.767858,HmiyD2TTLFNqkNe,34.381150,43.332853,0.358182
65,2020-05-15 16:15:00,4135001,99493.017857,9763.446429,128208.535714,HmiyD2TTLFNqkNe,34.126257,41.007432,0.328896
66,2020-05-15 16:30:00,4135001,104079.607143,10210.664286,130816.017856,HmiyD2TTLFNqkNe,34.356610,41.280591,0.344954
67,2020-05-15 16:45:00,4135001,77777.196429,7643.759524,133059.166667,HmiyD2TTLFNqkNe,33.861597,39.419076,0.260347
68,2020-05-15 17:00:00,4135001,49913.767857,4894.992857,134620.839284,HmiyD2TTLFNqkNe,33.443314,36.826704,0.166813
69,2020-05-15 17:15:00,4135001,49718.660716,4875.005357,135859.303572,HmiyD2TTLFNqkNe,33.300255,35.852207,0.173899
70,2020-05-15 17:30:00,4135001,26248.833333,2558.016667,136646.750000,HmiyD2TTLFNqkNe,33.032122,34.338400,0.087162
71,2020-05-15 17:45:00,4135001,11391.250000,1102.005357,137121.857143,HmiyD2TTLFNqkNe,32.311871,31.548539,0.038403
72,2020-05-15 18:00:00,4135001,6505.000000,628.376786,137350.446429,HmiyD2TTLFNqkNe,31.132414,30.225331,0.022545
73,2020-05-15 18:15:00,4135001,2199.217857,212.151786,137449.607144,HmiyD2TTLFNqkNe,29.243111,28.682507,0.009150
74,2020-05-15 18:30:00,4135001,0.000000,0.000000,137473.000000,HmiyD2TTLFNqkNe,28.495518,27.285992,0.001841

In [509]:
spd2['SOURCE_KEY'] = spd2['SOURCE_KEY'].astype('string')

spd2 = spd2.rename(columns={'DATE_TIME': 'Timestamp', 'SolarPlantData1.ipynb' 'IRRIDATION': 'Irradiation', 
                            'AMBIENT_TEMPERATURE': 'Ambient_Temperature', 'MODULE_TEMPERATURE': 'Module_Temperature', 
                            'DAILY_YIELD': 'Power_Generation'})

spd2.drop(columns=['SOURCE_KEY', 'DC_POWER', 'AC_POWER'], inplace=True)

In [510]:
spd2.head(10)

,Timestamp,PLANT_ID,Power_Generation,Ambient_Temperature,Module_Temperature,IRRADIATION
0,2020-05-15 00:00:00,4135001,0.0,25.184316,22.857507,0.0
1,2020-05-15 00:15:00,4135001,0.0,25.084589,22.761668,0.0
2,2020-05-15 00:30:00,4135001,0.0,24.935753,22.592306,0.0
3,2020-05-15 00:45:00,4135001,0.0,24.846130,22.360852,0.0
4,2020-05-15 01:00:00,4135001,0.0,24.621525,22.165423,0.0
5,2020-05-15 01:15:00,4135001,0.0,24.536092,21.968571,0.0
6,2020-05-15 01:30:00,4135001,0.0,24.638674,22.352926,0.0
7,2020-05-15 01:45:00,4135001,0.0,24.873022,23.160919,0.0
8,2020-05-15 02:00:00,4135001,0.0,24.936930,23.026113,0.0
9,2020-05-15 02:15:00,4135001,0.0,25.012248,23.343229,0.0

In [511]:
spd2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6417 entries, 0 to 6416
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Timestamp            6417 non-null   datetime64[ns]
 1   PLANT_ID             6417 non-null   int64
 2   Power_Generation     6417 non-null   float64
 3   Ambient_Temperature  6416 non-null   float64
 4   Module_Temperature   6416 non-null   float64
 5   IRRADIATION          6416 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(1)
memory usage: 300.9 KB

In [512]:
spd2.isna().any()

Timestamp              False
PLANT_ID               False
Power_Generation       False
Ambient_Temperature     True
Module_Temperature      True
IRRADIATION             True
dtype: bool

In [513]:
spd2[spd2.isna().any(axis=1)].index[0]

1776

In [514]:
spd2.iloc[1770:1781]

,Timestamp,PLANT_ID,Power_Generation,Ambient_Temperature,Module_Temperature,IRRADIATION
1770,2020-06-03 12:30:00,4135001,82882.321429,28.570162,49.940275,0.811303
1771,2020-06-03 12:45:00,4135001,89147.517856,28.792798,51.433227,0.896162
1772,2020-06-03 13:00:00,4135001,95491.482142,29.067692,51.646177,0.799893
1773,2020-06-03 13:15:00,4135001,100963.785715,28.884843,48.988139,0.711361
1774,2020-06-03 13:30:00,4135001,106477.714286,28.559281,48.776688,0.750453
1775,2020-06-03 13:45:00,4135001,109848.666666,27.862188,46.631439,0.615273
1776,2020-06-03 14:00:00,4135001,22406.000000,NaN,NaN,NaN
1777,2020-06-03 14:15:00,4135001,123811.250000,28.361993,50.627043,0.716680
1778,2020-06-03 14:30:00,4135001,129244.571428,28.309357,47.377397,0.673312
1779,2020-06-03 14:45:00,4135001,134089.250000,28.278159,45.068170,0.730956
1780,2020-06-03 15:00:00,4135001,140255.678572,28.846633,50.686334,0.867351

In [515]:
spd2.loc[1776]

Timestamp              2020-06-03 14:00:00
PLANT_ID                           4135001
Power_Generation                   22406.0
Ambient_Temperature                    NaN
Module_Temperature                     NaN
IRRADIATION                            NaN
Name: 1776, dtype: object

In [516]:
spd2 = spd2.dropna().reset_index(drop=True)
spd2.iloc[1774:1777]

,Timestamp,PLANT_ID,Power_Generation,Ambient_Temperature,Module_Temperature,IRRADIATION
1774,2020-06-03 13:30:00,4135001,106477.714286,28.559281,48.776688,0.750453
1775,2020-06-03 13:45:00,4135001,109848.666666,27.862188,46.631439,0.615273
1776,2020-06-03 14:15:00,4135001,123811.250000,28.361993,50.627043,0.716680

In [517]:
spd2.isna().any()

Timestamp              False
PLANT_ID               False
Power_Generation       False
Ambient_Temperature    False
Module_Temperature     False
IRRADIATION            False
dtype: bool